trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - pipeline.yaml

pool: amey-vmpool

stages:
- stage:
  jobs:
  - job: Deploy
    displayName: Kubernetes Sample Deployment
    pool: amey-vmpool
    steps:
    - task: Kubernetes@0
      displayName: 'Deploy NGINX Application'
      inputs:
        kubernetesServiceConnection: 'amey-aks-svc-con'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/Dep'